<?php

namespace ContainerK4ogJ62;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAdressControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserAdressController' shared autowired service.
     *
     * @return \App\Controller\UserAdressController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserAdressController.php';

        $container->services['App\\Controller\\UserAdressController'] = $instance = new \App\Controller\UserAdressController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\UserAdressController', $container));

        return $instance;
    }
}
