<?php

namespace ContainerYuZZNyW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdressFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\AdressFormType' shared autowired service.
     *
     * @return \App\Form\AdressFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\AdressFormType'] = new \App\Form\AdressFormType();
    }
}
