controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\SecurityController::login

home: 
    path: /home
    controller: App\Controller\HomeController::index

adress:
    path: /user_adress
    controller: App\Controller\UserAdressController::index