<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container54Uz9Lw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container54Uz9Lw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container54Uz9Lw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container54Uz9Lw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container54Uz9Lw\App_KernelDevDebugContainer([
    'container.build_hash' => '54Uz9Lw',
    'container.build_id' => '0c97c868',
    'container.build_time' => 1645294701,
], __DIR__.\DIRECTORY_SEPARATOR.'Container54Uz9Lw');
