<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0qyjlg9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0qyjlg9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0qyjlg9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0qyjlg9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0qyjlg9\App_KernelDevDebugContainer([
    'container.build_hash' => '0qyjlg9',
    'container.build_id' => '5bed5b36',
    'container.build_time' => 1645900197,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0qyjlg9');
